In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 1.1 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/12.7 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.7 MB 1.3 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.7 MB 868.0 kB/s eta 0:00:14
   --- ------------------------------------ 1.0/12.7 MB 868.


[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [20]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.reshape((5,1))

[1 2 3 4 5]


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)

(2, 5)


In [10]:
arr2[-1,2:4]

array([4, 5])

In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr3 = np.array([[1,2,3],[4,5,6]])

print(f'Array:\n {arr3}')
print(f'Shape: {arr3.shape}')
print(f'Number of dimensions: {arr3.ndim}')
print(f'Size (number of elements): {arr3.size}')
print(f'Data type: {arr3.dtype}')
print(f'Items size (in bytes): {arr3.itemsize}')

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Items size (in bytes): 8


In [ ]:
#Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#addition
print("Addition:", arr1+arr2)

#Subtraction
print("Subtraction:", arr1-arr2)

#Multiplication
print("Multiplication:", arr1*arr2)

#Division
print("Division:", arr2/arr1)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.] 0


In [41]:
#Universal Function
arr=np.array([4,5,6])

#Square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[2.         2.23606798 2.44948974]
[ 54.59815003 148.4131591  403.42879349]
[-0.7568025  -0.95892427 -0.2794155 ]
[1.38629436 1.60943791 1.79175947]


In [44]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array: \n', arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
arr[0][0] = 100

In [50]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [51]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
#Statistical concepts--Normalization
#To have a mean 0 and Standard deviation 1
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print('Normalized data:', normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [56]:
data = np.array([1,2,3,4,5,6,7,8])

#mean
mean= np.mean(data)
print(mean)

#median
median=np.median(data)
print(median)

#standard deviation
std_dev=np.std(data)
print(std_dev)

#Variance
variance=np.var(data)
print(variance)

4.5
4.5
2.29128784747792
5.25


In [66]:
#logical operator
arr4 = np.array([1,2,3,4,5,6,7,8,9])

arr4[(arr4>4) & (arr4<7)]

array([5, 6])